version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: drupal_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: drupal
      POSTGRES_PASSWORD: drupalpass
    volumes:
      - drupal-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  drupal:
    build: .
    image: custom-drupal
    container_name: drupal_app
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DRUPAL_DB_DRIVER: pgsql
      DRUPAL_DB_HOST: postgres
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupal
      DRUPAL_DB_PASSWORD: drupalpass
    ports:
      - "8080:80"
    volumes:
      - drupal-data:/var/www/html

volumes:
  drupal-db:
  drupal-data:
